#!/bin/bash
##===----------------------------------------------------------------------===##
##
## This source file is part of the Swift open source project
##
## Copyright (c) 2014-2022 Apple Inc. and the Swift project authors
## Licensed under Apache License v2.0 with Runtime Library Exception
##
## See http://swift.org/LICENSE.txt for license information
## See http://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
##
##===----------------------------------------------------------------------===##

set -eu

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${__dir}/.."
echo "Current directory is ${PWD}"

CONFIGURATION=${CONFIGURATION:-debug}
export SWIFTCI_IS_SELF_HOSTED=1

set -x

# Display toolchain version
 swift --version

# Perform package update in order to get the latest commits for the dependencies.
swift package update
swift build -c $CONFIGURATION
swift test -c $CONFIGURATION --parallel

# Build/Run the the project using the swift-build and swift-test executable targets we just built with SwiftPM.
export SWIFTPM_BIN_DIR=$(swift build -c $CONFIGURATION --show-bin-path)
$SWIFTPM_BIN_DIR/swift-build
$SWIFTPM_BIN_DIR/swift-test --parallel

if [ "$(uname)" == "Darwin" ]; then
  cd ..
  echo "Current working directory is ${PWD}"
  echo "Bootstrapping with the XCBuild codepath..."
  ./Utilities/bootstrap build --release \
    --cross-compile-hosts macosx-arm64 \
    --skip-cmake-bootstrap \
    --swift-build-path "${SWIFTPM_BIN_DIR}/swift-build"
fi
